<?php

namespace App\Http\Controllers\Api\Permission;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\PermissionModel;
use Illuminate\Support\Facades\DB;


class PermissionController extends Controller
{



  public function index()
  {
      $getdata = DB::table('permission')->whereNull('deleted_at')->get();

      return $getdata->toJson();
  }
    public function getPermission(Request $request)
    {
        $getpermission = DB::table('permission')->where('id',$request->permission_id)->first();

        return response()->json(compact('getpermission'));
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
          'permission_name' => 'required|unique:permission|max:255',
          'ManageUser' => 'required|boolean',
          'ManageUserView' => 'required|boolean',
          'ManageUserEdit' => 'required|boolean',
          'ManageUserDelete' => 'required|boolean',
          'ManagePermission' => 'required|boolean',
          'ManagePermissionView' => 'required|boolean',
          'ManagePermissionEdit' => 'required|boolean',
          'ManagePermissionDelete' => 'required|boolean',
          'ManageAddress' => 'required|boolean',
          'ManageAddressView' => 'required|boolean',
          'ManageAddressEdit' => 'required|boolean',
          'ManageAddressDelete' => 'required|boolean',
          'ManageCompany' => 'required|boolean',
          'ManageCompanyView' => 'required|boolean',
          'ManageCompanyEdit' => 'required|boolean',
          'ManageCompanyDelete' => 'required|boolean',
          'ManageDepartment' => 'required|boolean',
          'ManageDepartmentView' => 'required|boolean',
          'ManageDepartmentEdit' => 'required|boolean',
          'ManageDepartmentDelete' => 'required|boolean',
          'ManageDistrict' => 'required|boolean',
          'ManageDistrictView' => 'required|boolean',
          'ManageDistrictEdit' => 'required|boolean',
          'ManageDistrictDelete' => 'required|boolean',
          'ManageEquipment' => 'required|boolean',
          'ManageEquipmentView' => 'required|boolean',
          'ManageEquipmentEdit' => 'required|boolean',
          'ManageEquipmentDelete' => 'required|boolean',
          'ManageImage' => 'required|boolean',
          'ManageImageView' => 'required|boolean',
          'ManageImageEdit' => 'required|boolean',
          'ManageImageDelete' => 'required|boolean',
          'ManageImpact' => 'required|boolean',
          'ManageImpactView' => 'required|boolean',
          'ManageImpactEdit' => 'required|boolean',
          'ManageImpactDelete' => 'required|boolean',
          'ManageLocation' => 'required|boolean',
          'ManageLocationView' => 'required|boolean',
          'ManageLocationEdit' => 'required|boolean',
          'ManageLocationDelete' => 'required|boolean',
          'ManageMessage' => 'required|boolean',
          'ManageMessageView' => 'required|boolean',
          'ManageMessageEdit' => 'required|boolean',
          'ManageMessageDelete' => 'required|boolean',
          'ManageModify' => 'required|boolean',
          'ManageModifyView' => 'required|boolean',
          'ManageModifyEdit' => 'required|boolean',
          'ManageModifyDelete' => 'required|boolean',
          'ManageNews' => 'required|boolean',
          'ManageNewsView' => 'required|boolean',
          'ManageNewsEdit' => 'required|boolean',
          'ManageNewsDelete' => 'required|boolean',
          'ManagePersonContact' => 'required|boolean',
          'ManagePersonContactView' => 'required|boolean',
          'ManagePersonContactEdit' => 'required|boolean',
          'ManagePersonContactDelete' => 'required|boolean',
          'ManagePersonResponsible' => 'required|boolean',
          'ManagePersonResponsibleView' => 'required|boolean',
          'ManagePersonResponsibleEdit' => 'required|boolean',
          'ManagePersonResponsibleDelete' => 'required|boolean',
          'ManagePostalCode' => 'required|boolean',
          'ManagePostalCodeView' => 'required|boolean',
          'ManagePostalCodeEdit' => 'required|boolean',
          'ManagePostalCodeDelete' => 'required|boolean',
          'ManagePriority' => 'required|boolean',
          'ManagePriorityView' => 'required|boolean',
          'ManagePriorityEdit' => 'required|boolean',
          'ManagePriorityDelete' => 'required|boolean',
          'ManageProvince' => 'required|boolean',
          'ManageProvinceView' => 'required|boolean',
          'ManageProvinceEdit' => 'required|boolean',
          'ManageProvinceDelete' => 'required|boolean',
          'ManageRequestGeneral' => 'required|boolean',
          'ManageRequestGeneralView' => 'required|boolean',
          'ManageRequestGeneralEdit' => 'required|boolean',
          'ManageRequestGeneralDelete' => 'required|boolean',
          'ManageRequestIssuses' => 'required|boolean',
          'ManageRequestIssusesView' => 'required|boolean',
          'ManageRequestIssusesEdit' => 'required|boolean',
          'ManageRequestIssusesDelete' => 'required|boolean',
          'ManageSettingNews' => 'required|boolean',
          'ManageSettingNewsView' => 'required|boolean',
          'ManageSettingNewsEdit' => 'required|boolean',
          'ManageSettingNewsDelete' => 'required|boolean',
          'Report' => 'required|boolean'


   ]);

      $insert =   PermissionModel::create([
     'permission_name' => $validatedData['permission_name'],
     'ManageUser' => $validatedData['ManageUser'],
     'ManageUserView' => $validatedData['ManageUserView'],
     'ManageUserEdit' => $validatedData['ManageUserEdit'],
     'ManageUserDelete' => $validatedData['ManageUserDelete'],
     'ManagePermission' => $validatedData['ManagePermission'],
     'ManagePermissionView' => $validatedData['ManagePermissionView'],
     'ManagePermissionEdit' => $validatedData['ManagePermissionEdit'],
     'ManagePermissionDelete' => $validatedData['ManagePermissionDelete'],
     'ManageAddress' => $validatedData['ManageAddress'],
     'ManageAddressView' => $validatedData['ManageAddressView'],
     'ManageAddressEdit' => $validatedData['ManageAddressEdit'],
     'ManageAddressDelete' => $validatedData['ManageAddressDelete'],
     'ManageCompany' => $validatedData['ManageCompany'],
     'ManageCompanyView' => $validatedData['ManageCompanyView'],
     'ManageCompanyEdit' => $validatedData['ManageCompanyEdit'],
     'ManageCompanyDelete' => $validatedData['ManageCompanyDelete'],
     'ManageDepartment' => $validatedData['ManageDepartment'],
     'ManageDepartmentView' => $validatedData['ManageDepartmentView'],
     'ManageDepartmentEdit' => $validatedData['ManageDepartmentEdit'],
     'ManageDepartmentDelete' => $validatedData['ManageDepartmentDelete'],
     'ManageDistrict' => $validatedData['ManageDistrict'],
     'ManageDistrictView' => $validatedData['ManageDistrictView'],
     'ManageDistrictEdit' => $validatedData['ManageDistrictEdit'],
     'ManageDistrictDelete' => $validatedData['ManageDistrictDelete'],
     'ManageEquipment' => $validatedData['ManageEquipment'],
     'ManageEquipmentView' => $validatedData['ManageEquipmentView'],
     'ManageEquipmentEdit' => $validatedData['ManageEquipmentEdit'],
     'ManageEquipmentDelete' => $validatedData['ManageEquipmentDelete'],
     'ManageImage' => $validatedData['ManageImage'],
     'ManageImageView' => $validatedData['ManageImageView'],
     'ManageImageEdit' => $validatedData['ManageImageEdit'],
     'ManageImageDelete' => $validatedData['ManageImageDelete'],
     'ManageImpact' => $validatedData['ManageImpact'],
     'ManageImpactView' => $validatedData['ManageImpactView'],
     'ManageImpactEdit' => $validatedData['ManageImpactEdit'],
     'ManageImpactDelete' => $validatedData['ManageImpactDelete'],
     'ManageLocation' => $validatedData['ManageLocation'],
     'ManageLocationView' => $validatedData['ManageLocationView'],
     'ManageLocationEdit' => $validatedData['ManageLocationEdit'],
     'ManageLocationDelete' => $validatedData['ManageLocationDelete'],
     'ManageMessage' => $validatedData['ManageMessage'],
     'ManageMessageView' => $validatedData['ManageMessageView'],
     'ManageMessageEdit' => $validatedData['ManageMessageEdit'],
     'ManageMessageDelete' => $validatedData['ManageMessageDelete'],
     'ManageModify' => $validatedData['ManageModify'],
     'ManageModifyView' => $validatedData['ManageModifyView'],
     'ManageModifyEdit' => $validatedData['ManageModifyEdit'],
     'ManageModifyDelete' => $validatedData['ManageModifyDelete'],
     'ManageNews' => $validatedData['ManageNews'],
     'ManageNewsView' => $validatedData['ManageNewsView'],
     'ManageNewsEdit' => $validatedData['ManageNewsEdit'],
     'ManageNewsDelete' => $validatedData['ManageNewsDelete'],
     'ManagePersonContact' => $validatedData['ManagePersonContact'],
     'ManagePersonContactView' => $validatedData['ManagePersonContactView'],
     'ManagePersonContactEdit' => $validatedData['ManagePersonContactEdit'],
     'ManagePersonContactDelete' => $validatedData['ManagePersonContactDelete'],
     'ManagePersonResponsible' => $validatedData['ManagePersonResponsible'],
     'ManagePersonResponsibleView' => $validatedData['ManagePersonResponsibleView'],
     'ManagePersonResponsibleEdit' => $validatedData['ManagePersonResponsibleEdit'],
     'ManagePersonResponsibleDelete' => $validatedData['ManagePersonResponsibleDelete'],
     'ManagePostalCode' => $validatedData['ManagePostalCode'],
     'ManagePostalCodeView' => $validatedData['ManagePostalCodeView'],
     'ManagePostalCodeEdit' => $validatedData['ManagePostalCodeEdit'],
     'ManagePostalCodeDelete' => $validatedData['ManagePostalCodeDelete'],
     'ManagePriority' => $validatedData['ManagePriority'],
     'ManagePriorityView' => $validatedData['ManagePriorityView'],
     'ManagePriorityEdit' => $validatedData['ManagePriorityEdit'],
     'ManagePriorityDelete' => $validatedData['ManagePriorityDelete'],
     'ManageProvince' => $validatedData['ManageProvince'],
     'ManageProvinceView' => $validatedData['ManageProvinceView'],
     'ManageProvinceEdit' => $validatedData['ManageProvinceEdit'],
     'ManageProvinceDelete' => $validatedData['ManageProvinceDelete'],
     'ManageRequestGeneral' => $validatedData['ManageRequestGeneral'],
     'ManageRequestGeneralView' => $validatedData['ManageRequestGeneralView'],
     'ManageRequestGeneralEdit' => $validatedData['ManageRequestGeneralEdit'],
     'ManageRequestGeneralDelete' => $validatedData['ManageRequestGeneralDelete'],
     'ManageRequestIssuses' => $validatedData['ManageRequestIssuses'],
     'ManageRequestIssusesView' => $validatedData['ManageRequestIssusesView'],
     'ManageRequestIssusesEdit' => $validatedData['ManageRequestIssusesEdit'],
     'ManageRequestIssusesDelete' => $validatedData['ManageRequestIssusesDelete'],
     'ManageSettingNews' => $validatedData['ManageSettingNews'],
     'ManageSettingNewsView' => $validatedData['ManageSettingNewsView'],
     'ManageSettingNewsEdit' => $validatedData['ManageSettingNewsEdit'],
     'ManageSettingNewsDelete' => $validatedData['ManageSettingNewsDelete'],
     'Report' => $validatedData['Report']

   ]);

      return response()->json(compact('insert'));
    }

    public function edit($id)
    {
        $listdata = DB::table('permission')->whereNull('deleted_at')->orWhere('id', $id)->get();

        return $listdata->toJson();
    }

    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
          'permission_name' => 'required|unique:permission|max:255',
          'ManageUser' => 'required|boolean',
          'ManageUserView' => 'required|boolean',
          'ManageUserEdit' => 'required|boolean',
          'ManageUserDelete' => 'required|boolean',
          'ManagePermission' => 'required|boolean',
          'ManagePermissionView' => 'required|boolean',
          'ManagePermissionEdit' => 'required|boolean',
          'ManagePermissionDelete' => 'required|boolean',
          'ManageAddress' => 'required|boolean',
          'ManageAddressView' => 'required|boolean',
          'ManageAddressEdit' => 'required|boolean',
          'ManageAddressDelete' => 'required|boolean',
          'ManageCompany' => 'required|boolean',
          'ManageCompanyView' => 'required|boolean',
          'ManageCompanyEdit' => 'required|boolean',
          'ManageCompanyDelete' => 'required|boolean',
          'ManageDepartment' => 'required|boolean',
          'ManageDepartmentView' => 'required|boolean',
          'ManageDepartmentEdit' => 'required|boolean',
          'ManageDepartmentDelete' => 'required|boolean',
          'ManageDistrict' => 'required|boolean',
          'ManageDistrictView' => 'required|boolean',
          'ManageDistrictEdit' => 'required|boolean',
          'ManageDistrictDelete' => 'required|boolean',
          'ManageEquipment' => 'required|boolean',
          'ManageEquipmentView' => 'required|boolean',
          'ManageEquipmentEdit' => 'required|boolean',
          'ManageEquipmentDelete' => 'required|boolean',
          'ManageImage' => 'required|boolean',
          'ManageImageView' => 'required|boolean',
          'ManageImageEdit' => 'required|boolean',
          'ManageImageDelete' => 'required|boolean',
          'ManageImpact' => 'required|boolean',
          'ManageImpactView' => 'required|boolean',
          'ManageImpactEdit' => 'required|boolean',
          'ManageImpactDelete' => 'required|boolean',
          'ManageLocation' => 'required|boolean',
          'ManageLocationView' => 'required|boolean',
          'ManageLocationEdit' => 'required|boolean',
          'ManageLocationDelete' => 'required|boolean',
          'ManageMessage' => 'required|boolean',
          'ManageMessageView' => 'required|boolean',
          'ManageMessageEdit' => 'required|boolean',
          'ManageMessageDelete' => 'required|boolean',
          'ManageModify' => 'required|boolean',
          'ManageModifyView' => 'required|boolean',
          'ManageModifyEdit' => 'required|boolean',
          'ManageModifyDelete' => 'required|boolean',
          'ManageNews' => 'required|boolean',
          'ManageNewsView' => 'required|boolean',
          'ManageNewsEdit' => 'required|boolean',
          'ManageNewsDelete' => 'required|boolean',
          'ManagePersonContact' => 'required|boolean',
          'ManagePersonContactView' => 'required|boolean',
          'ManagePersonContactEdit' => 'required|boolean',
          'ManagePersonContactDelete' => 'required|boolean',
          'ManagePersonResponsible' => 'required|boolean',
          'ManagePersonResponsibleView' => 'required|boolean',
          'ManagePersonResponsibleEdit' => 'required|boolean',
          'ManagePersonResponsibleDelete' => 'required|boolean',
          'ManagePostalCode' => 'required|boolean',
          'ManagePostalCodeView' => 'required|boolean',
          'ManagePostalCodeEdit' => 'required|boolean',
          'ManagePostalCodeDelete' => 'required|boolean',
          'ManagePriority' => 'required|boolean',
          'ManagePriorityView' => 'required|boolean',
          'ManagePriorityEdit' => 'required|boolean',
          'ManagePriorityDelete' => 'required|boolean',
          'ManageProvince' => 'required|boolean',
          'ManageProvinceView' => 'required|boolean',
          'ManageProvinceEdit' => 'required|boolean',
          'ManageProvinceDelete' => 'required|boolean',
          'ManageRequestGeneral' => 'required|boolean',
          'ManageRequestGeneralView' => 'required|boolean',
          'ManageRequestGeneralEdit' => 'required|boolean',
          'ManageRequestGeneralDelete' => 'required|boolean',
          'ManageRequestIssuses' => 'required|boolean',
          'ManageRequestIssusesView' => 'required|boolean',
          'ManageRequestIssusesEdit' => 'required|boolean',
          'ManageRequestIssusesDelete' => 'required|boolean',
          'ManageSettingNews' => 'required|boolean',
          'ManageSettingNewsView' => 'required|boolean',
          'ManageSettingNewsEdit' => 'required|boolean',
          'ManageSettingNewsDelete' => 'required|boolean',
          'Report' => 'required|boolean',

   ]);

        PermissionModel::findOrFail($id)
            ->update([
              'permission_name' => $validatedData['permission_name'],
              'ManageUser' => $validatedData['ManageUser'],
              'ManageUserView' => $validatedData['ManageUserView'],
              'ManageUserEdit' => $validatedData['ManageUserEdit'],
              'ManageUserDelete' => $validatedData['ManageUserDelete'],
              'ManagePermission' => $validatedData['ManagePermission'],
              'ManagePermissionView' => $validatedData['ManagePermissionView'],
              'ManagePermissionEdit' => $validatedData['ManagePermissionEdit'],
              'ManagePermissionDelete' => $validatedData['ManagePermissionDelete'],
              'ManageAddress' => $validatedData['ManageAddress'],
              'ManageAddressView' => $validatedData['ManageAddressView'],
              'ManageAddressEdit' => $validatedData['ManageAddressEdit'],
              'ManageAddressDelete' => $validatedData['ManageAddressDelete'],
              'ManageCompany' => $validatedData['ManageCompany'],
              'ManageCompanyView' => $validatedData['ManageCompanyView'],
              'ManageCompanyEdit' => $validatedData['ManageCompanyEdit'],
              'ManageCompanyDelete' => $validatedData['ManageCompanyDelete'],
              'ManageDepartment' => $validatedData['ManageDepartment'],
              'ManageDepartmentView' => $validatedData['ManageDepartmentView'],
              'ManageDepartmentEdit' => $validatedData['ManageDepartmentEdit'],
              'ManageDepartmentDelete' => $validatedData['ManageDepartmentDelete'],
              'ManageDistrict' => $validatedData['ManageDistrict'],
              'ManageDistrictView' => $validatedData['ManageDistrictView'],
              'ManageDistrictEdit' => $validatedData['ManageDistrictEdit'],
              'ManageDistrictDelete' => $validatedData['ManageDistrictDelete'],
              'ManageEquipment' => $validatedData['ManageEquipment'],
              'ManageEquipmentView' => $validatedData['ManageEquipmentView'],
              'ManageEquipmentEdit' => $validatedData['ManageEquipmentEdit'],
              'ManageEquipmentDelete' => $validatedData['ManageEquipmentDelete'],
              'ManageImage' => $validatedData['ManageImage'],
              'ManageImageView' => $validatedData['ManageImageView'],
              'ManageImageEdit' => $validatedData['ManageImageEdit'],
              'ManageImageDelete' => $validatedData['ManageImageDelete'],
              'ManageImpact' => $validatedData['ManageImpact'],
              'ManageImpactView' => $validatedData['ManageImpactView'],
              'ManageImpactEdit' => $validatedData['ManageImpactEdit'],
              'ManageImpactDelete' => $validatedData['ManageImpactDelete'],
              'ManageLocation' => $validatedData['ManageLocation'],
              'ManageLocationView' => $validatedData['ManageLocationView'],
              'ManageLocationEdit' => $validatedData['ManageLocationEdit'],
              'ManageLocationDelete' => $validatedData['ManageLocationDelete'],
              'ManageMessage' => $validatedData['ManageMessage'],
              'ManageMessageView' => $validatedData['ManageMessageView'],
              'ManageMessageEdit' => $validatedData['ManageMessageEdit'],
              'ManageMessageDelete' => $validatedData['ManageMessageDelete'],
              'ManageModify' => $validatedData['ManageModify'],
              'ManageModifyView' => $validatedData['ManageModifyView'],
              'ManageModifyEdit' => $validatedData['ManageModifyEdit'],
              'ManageModifyDelete' => $validatedData['ManageModifyDelete'],
              'ManageNews' => $validatedData['ManageNews'],
              'ManageNewsView' => $validatedData['ManageNewsView'],
              'ManageNewsEdit' => $validatedData['ManageNewsEdit'],
              'ManageNewsDelete' => $validatedData['ManageNewsDelete'],
              'ManagePersonContact' => $validatedData['ManagePersonContact'],
              'ManagePersonContactView' => $validatedData['ManagePersonContactView'],
              'ManagePersonContactEdit' => $validatedData['ManagePersonContactEdit'],
              'ManagePersonContactDelete' => $validatedData['ManagePersonContactDelete'],
              'ManagePersonResponsible' => $validatedData['ManagePersonResponsible'],
              'ManagePersonResponsibleView' => $validatedData['ManagePersonResponsibleView'],
              'ManagePersonResponsibleEdit' => $validatedData['ManagePersonResponsibleEdit'],
              'ManagePersonResponsibleDelete' => $validatedData['ManagePersonResponsibleDelete'],
              'ManagePostalCode' => $validatedData['ManagePostalCode'],
              'ManagePostalCodeView' => $validatedData['ManagePostalCodeView'],
              'ManagePostalCodeEdit' => $validatedData['ManagePostalCodeEdit'],
              'ManagePostalCodeDelete' => $validatedData['ManagePostalCodeDelete'],
              'ManagePriority' => $validatedData['ManagePriority'],
              'ManagePriorityView' => $validatedData['ManagePriorityView'],
              'ManagePriorityEdit' => $validatedData['ManagePriorityEdit'],
              'ManagePriorityDelete' => $validatedData['ManagePriorityDelete'],
              'ManageProvince' => $validatedData['ManageProvince'],
              'ManageProvinceView' => $validatedData['ManageProvinceView'],
              'ManageProvinceEdit' => $validatedData['ManageProvinceEdit'],
              'ManageProvinceDelete' => $validatedData['ManageProvinceDelete'],
              'ManageRequestGeneral' => $validatedData['ManageRequestGeneral'],
              'ManageRequestGeneralView' => $validatedData['ManageRequestGeneralView'],
              'ManageRequestGeneralEdit' => $validatedData['ManageRequestGeneralEdit'],
              'ManageRequestGeneralDelete' => $validatedData['ManageRequestGeneralDelete'],
              'ManageRequestIssuses' => $validatedData['ManageRequestIssuses'],
              'ManageRequestIssusesView' => $validatedData['ManageRequestIssusesView'],
              'ManageRequestIssusesEdit' => $validatedData['ManageRequestIssusesEdit'],
              'ManageRequestIssusesDelete' => $validatedData['ManageRequestIssusesDelete'],
              'ManageSettingNews' => $validatedData['ManageSettingNews'],
              'ManageSettingNewsView' => $validatedData['ManageSettingNewsView'],
              'ManageSettingNewsEdit' => $validatedData['ManageSettingNewsEdit'],
              'ManageSettingNewsDelete' => $validatedData['ManageSettingNewsDelete'],
              'Report' => $validatedData['Report']
          ]);
    }

    public function destroy($id)
    {
      PermissionModel::destroy($id);
      return response()->json('delete successfully'.$id);
    }

    public function destroy_select(Request $request)
    {
      PermissionModel::destroy($request->foo);

      return response()->json([
     'data' => $request->foo,
   ]);
  }
}
